### ISSUE TITLE
jsome.level.show=true displaying "undefined" instead of level.char

### ISSUE THREAD

**Issue by akileez** [Javascipt/Jsome#1]
First of all, AWESOME work here!!!  :+1: Love your code and style. I am `that` guy who duplicated this precious gem with [json-colorz](https://github.com/akileez/json-colorz). I hope you take that as an honor.

In testing this latest version, came across a situation with the following setup:

``` js
var obj = {
  a: 1,
  b: 2,
  c: {
    d: {
      e: 3
    }
  }
}

jsome.level.show = true
jsome.level.spaces = 2
jsome.level.start = 2

jsome(obj)
```

which displays:

``` js
undefined undefined {
undefined undefined undefined a: 1,
undefined undefined undefined b: 2,
undefined undefined undefined c: {
undefined undefined undefined undefined d: {
undefined undefined undefined undefined undefined e: 3
undefined undefined undefined undefined }
undefined undefined undefined }
undefined undefined }
```

I think the problem originates from [this line](https://github.com/Javascipt/Jsome/blob/master/lib/generator.js#L41)

maybe you wish to do something like the following...

``` js
levelStr = levelStr.replace(' ', useColorProvider(opts.char, opts.color))
```

or, maybe you have other plans yet to be implemented. just wanted you to be aware if you were not.

**Comment by Javascipt** [comment]
Hello Akileez, I'm very happy that you took some time to read my code and find this bug :) ! I'm also very happy that you duplicated this package, you are free to do so :) you have all the rights ! 

I've corrected this bug using your help :+1: (https://github.com/Javascipt/Jsome/commit/de38e32af2d2b463a175ef55082870bb5ff900a6). 
Thanks again.

I may need your help if you want to contribute. please check out this issue https://github.com/Javascipt/Jsome/issues/2

Feel free to make a Pull Request though !

I have the same problem not only on this package but [detail](https://github.com/Javascipt/detail) and [soon](https://github.com/Javascipt/soon). As I said feel free to make a Pull Request. 

Thanks again

**Comment by akileez** [comment]
I responded to the other request. will do a pull-request if you need it but it should be a simple fix in your editor and another push to git.

**Comment by Javascipt** [comment]
Thank you for you help again, I really struggled more than 20 days to find out !! please make a Pull Request to be part of this project :)

**Comment by akileez** [comment]
no problem. give me some time. I need to brush up on Pull request. haven't done one in two years.

**Comment by Javascipt** [comment]
It's ok :) , I haven't done a lot of PR too. This is what I do :
- fork the repo
- clone it on your machine
- make changes + commit + push to your repo
- click on Pull Request button

**Comment by akileez** [comment]
beautiful :smile: thanks for that. give me a few mins then.

**Comment by Javascipt** [comment]
Take your time mate :+1:

**Comment by akileez** [comment]
Submitted pull-request. The file mode was changed from 644 to 755. This is because I copied the file I edited in the global install package of Jsome. When I forked the repo and cloned to my machine, the file in question was already set to unix LF endings so there was nothing to edit on my end. 

Just downloaded from my repo and tested. everything ran file
