### ISSUE TITLE
jsome-cli

### ISSUE THREAD

**Issue by Javascipt** [Javascipt/Jsome#2]
I have tried to make a cli to this package to allow the user to print json files directly on the console using a command line, example : 

``` bash
 $ jsome /path/to/file.json
```

I have added the bin property on the package.json [here](https://github.com/Javascipt/Jsome/blob/master/package.json#L32), it points to this [file](https://github.com/Javascipt/Jsome/blob/master/bin/cli.js)

The issue I have is that after installing the package globally it works on Windows, but not on Linux, I haven't tried it on a Mac OS though. can someone help me with this issue ?

**Comment by akileez** [comment]
problem here is the `line endings` of the file. Windows uses I believe `\r` or `\r\n` while Mac OS and Linux use `\n`

![jsome_test](https://cloud.githubusercontent.com/assets/4314979/10651427/7974d402-781d-11e5-9a48-e388eb900c09.png)

you can see the `\r` after `node` when I ran this command. I changed the line ending in my editor to unix line endings and everything worked. you would need to do the same in your editor

**Comment by Javascipt** [comment]
Thank you again for your contribution https://github.com/Javascipt/Jsome/pull/3
It's merged. I'm going to publish it on npm in one minite. please try it on linux and let me know if it's ok.

**Comment by akileez** [comment]
no problem.

**Comment by Javascipt** [comment]
It's published, please give it a try :)

**Comment by akileez** [comment]
just tried it. doesn't work same as image above. what text editor do you use? I am assuming you are using a Windows machine, correct?

**Comment by Javascipt** [comment]
Yes, it's just my linux crached and doesn't work correctly anymore, that's why I switched temporarily to windows.

 I'm using [brackets.io](http://brackets.io/) editor.

**Comment by akileez** [comment]
![cli js jsome 2015-10-21 19-29-02](https://cloud.githubusercontent.com/assets/4314979/10653097/32f4b6fc-782a-11e5-90e5-25376ddae231.png)

ok, that makes some sense then. as you can see from the image, when I open up the file, towards the bottom of the image you will see the encoding and next to that the line endings (windows). Methinks brackets is changing the line endings for this file either during an atomic save, manual save or git save. check the settings for bracket.io first. you should be able to easily correct this within the editor. You could also try [SublimeText3](http://www.sublimetext.com) ... its free to use.

**Comment by Javascipt** [comment]
OK, I'll take a look at that tomorrow. It's 00:52 here in Morocco :) I need to get some sleep. We'll continue our discussion then to get this package work again.

Thank you again for your time and effort :)

**Comment by akileez** [comment]
sounds good.

**Comment by akileez** [comment]
[see here](https://raw.githubusercontent.com/zaggino/brackets-git/master/screenshots/settings-dialog.jpg)

take note of the setting: normalize line endings...make sure yours are the same. I am assuming you are using git within brackets.

**Comment by Javascipt** [comment]
Hi Akileez, I've just checked the option "Normalize line endings (to \n)" on my editor, I found that there was no diff so I just added a new line to commit and push the new file ... I have published it on npm as well, would you please give it a try and let me know if it worked or not !

**Comment by akileez** [comment]
just tested. same results. file is encoded with Windows line endings. tried a test with my editor and a dummy file configured as: 

``` js
#!/usr/bin/env node
var path = require('path')
var fs = require('fs')
var jclrz = require('./index')
var fp = process.argv.slice(2).shift()

console.log(toString.call(fp))
console.log(fp)
console.log(fp[0])

console.log(path.resolve(fp))

fs.exists(path.resolve(fp), function (err) {
// fs.access(path.resolve(fp), function (err) {
  if (!err) return jclrz({error: "file doesn't exists"})
  fs.readFile(path.resolve(fp), function (err, res) {
    if (err) return jclrz({error: err.message})
    jclrz.parse(res.toString())
  })
})
```

image show first time run as Unix line endings and second run as Windows line endings. only change was an editor setting.

![jsome-test](https://cloud.githubusercontent.com/assets/4314979/10678927/5ad91a3c-78e3-11e5-9afe-6e72c5f0a935.png)

don't mind the error message on the first run. I had changed the file name to idx2.json. but the fact you see the console trace lets you know it runs.

**Comment by akileez** [comment]
I have this setting in SublimeText3 for default_line_endings

``` js
{
    // Determines what character(s) are used to terminate each line in new files.
    // Valid values are 'system' (whatever the OS uses), 'windows' (CRLF) and
    // 'unix' (LF only).
    "default_line_ending": "system"
}
```

maybe you have something like this in brackets that is overriding...

**Comment by Javascipt** [comment]
I have the same setting in Sublime Text

``` javascript
    // Determines what character(s) are used to terminate each line in new files.
    // Valid values are 'system' (whatever the OS uses), 'windows' (CRLF) and
    // 'unix' (LF only).
    "default_line_ending": "system"
```

I tried to look for `\r` using sublime text search but I couldn't find it. However, when I look for `\n` it highlights all the new lines !!

**Comment by akileez** [comment]
then open the repo in Sublime Text. navigate to bin/cli.js and view it. at the bottom of the screen should be the line endings which the file is set to. if it is not, then go to the menu: `View`, scroll down to: `Line Endings` and check what it is for this file. If Windows switch to Unix. if this is the case you should have to save the file again. If it is Unix, then the conversion is happening somewhere with git.

**Comment by akileez** [comment]
check both the globally installed module and your git repo on your machine.

**Comment by Javascipt** [comment]
can you please try now ? 
I start hating windows so much :rage:

**Comment by akileez** [comment]
no go...still the same. and I feel you pain with Windows. 
I just check all the files in the `jsome` repo. Here are the file which have Windows Line Endings:
bin/cli.js
lib/generator.js
LICENSE
README.md
scripts.js
test.js

the remaining files are either Unix line endings or images.
most of these are probably not a problem when running in node but the cli.js will be as `#!/usr/bin/env` is trying to execute `node` but is finding `node\r`
I suggest changing the setting in Sublime Text from `system` to `unix` for `default_line_ending`... and do this in the Settings-User file as opposed to Settings-Default

**Comment by Javascipt** [comment]
Let's try again, this time I loaded the file on sublime text and I found that the line endings is set to Unix. can you please try to install it from npm again.

**Comment by akileez** [comment]
:+1:  :100: 
about to test. but I opened the file and it had Unix Line Endings. so it should be good.

**Comment by akileez** [comment]
command line working!!!

![jsome-test2](https://cloud.githubusercontent.com/assets/4314979/10680222/b0858cd8-78eb-11e5-94a0-4c4de91907bf.jpg)

**Comment by akileez** [comment]
about to test the rest of the api in my test folder...make sure all is good.

**Comment by Javascipt** [comment]
Thank GOD !! 

thank you for your help Akileez, really I had no clue where is the error. it was a pleasure to work with you, let's keep in touch for future collaboration :+1: 
Thank you again

**Comment by akileez** [comment]
everything else is :+1:

**Comment by akileez** [comment]
no problem. anytime. It would be a pleasure working with you. you know where to find me.

**Comment by Javascipt** [comment]
:+1:
